baseURL = "https://resume.cameronwhite.dev/"
languageCode = "en-us"
title = "Cameron White's Resume"

theme = "orbit"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true


[params]

# Meta
    description = "Cameron White's Resume"
    author = "Cameron White"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it's quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Cameron White"
        tagline = "Software Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: HireMe@cameronwhite.dev"
        title = "HireMe@cameronwhite.dev"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+5033473626"
        title = "+15033473626"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://resume.cameronwhite.dev"
        title = "resume.cameronwhite.dev"


        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/cameronbwhite"
        title = "linkedin.com/in/cameronbwhite"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Computer Science"
        college = "Portland State University"

        [[params.education.list]]
        degree = "General Studies"
        college = "Portland Community College"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "CrossFit"

        [[params.interests.list]]
        interest = "Bitcoin"

        [[params.interests.list]]
        interest = "Podcasting 2.0"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Dogs"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """I have experience working with many different programming languages, environments, and frameworks. 
        Most of my programming is done in Golang, Python, and Javascript.
        I have written a verity of software including data processing, identity management, mathematical libraries, 
        graphical interfaces, web applications, command line tools, as well as an assortment of utilities. 
        My DevOps experience is focused on managing Linux and AWS Services using the HashiStack. 
        My testing experience has been to unit and system/integration everything.
        """

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "4/2020 - 2/2022"
        company = "Tempo Inc."
        details = """Started Tempo as the only Backend Developer in San Francisco when the company had 20 people. 
        Helped grow the company to over 200 people through two rounds of venture capital. 
        Maintained and contributed to a monolithic Python/Flask application. 
        Built Backend APIs for an embedded React and Mobile Applications (iOS and Android).
        Built an Ecommerce solution involving Shopify and Stripe; migrated from legacy system.
        Transitioned the RESTFul API to a GraphQL API. 
        Built a serverless recommendations generation system. 
        Implemented OAuth2 Login and migration from legacy authorization system.
        Acted as the AWS Administrator."""

        [[params.jobs.list]]
        position = "Software Engineer II"
        dates = "1/2019 - 4/2020"
        company = "Akamai Technolgies Inc."
        details = """Developed a multi-tenet hosted login solution by adapting a lagacy product with new JavaScript and Golang code.
        Designed and developed a real-time guarantee-delivery event distribution system for webhooks; written in Golang, using RDS and deployed to AWS.
        Designed a microservice front-end system and developed some components using React. Helped integrate Janrain into the Akamai Edge.
        Tested with unittests and integration tests using Behave. """

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "12/2015 - 1/2019"
        company = "Janrain Inc."
        details = """Started by building integrations, command line tools, and data migration scripts. 
        Transitioned into writing configuration RESTFul APIs. 
        Built a configuration Angular Web Application with a team of contractors. 
        Worked on a Data Pipeline using Kinesis, lambda and RDS. Evolved from AWS Elastic Beanstalk to the Hashistack. 
        Tested with unittests and integration tests using Behave.
        """

        [[params.jobs.list]]
        position = "Dev Intern"
        dates = "1/2015 - 7/2015"
        company = "Jive Inc."
        details = """Worked on the front-end team on a large monolithic web application written in Java and JavaScript."""

        [[params.jobs.list]]
        position = "QA Intern"
        dates = "7/2014 - 1/2015"
        company = "Janrain Inc."
        details = """Built test suites for Python, Scala and Java. 
        Helped develop an Angular UI and wrote the unittests. 
        Introduced automated testing with Travis CI and Sauce Labs. """

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "99%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "75%"

        [[params.skills.list]]
        skill = "Golang"
        level = "75%"
                
        [[params.skills.list]]
        skill = "AWS"
        level = "85%"

        [[params.skills.list]]
        skill = "Linux/Shell"
        level = "85%"

        [[params.skills.list]]
        skill = "Flask"
        level = "95%"

        [[params.skills.list]]
        skill = "React"
        level = "75%"

        [[params.skills.list]]
        skill = "Angular"
        level = "75%"

        [[params.skills.list]]
        skill = "PostgreSQL"
        level = "85%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""